# Generated by Django 3.1.4 on 2020-12-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submit',
            name='genre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
